package com.ric.pet;

import android.app.*;import android.content.*;import android.graphics.Color;import android.graphics.PixelFormat;import android.media.AudioDeviceInfo;import android.media.AudioManager;import android.os.*;import android.provider.Settings;import android.view.*;import android.widget.*;import java.util.Random;

public class OverlayPetService extends Service{
 private static final int ID=77;private WindowManager wm;private FrameLayout root;private PetView pet;private TextView bubble;private WindowManager.LayoutParams lp;private final Handler h=new Handler(Looper.getMainLooper());private final Random rng=new Random();private final PetNeeds needs=new PetNeeds();private CatSoundEngine sounds;private AudioManager audio;private int screenW,screenH,box;private float downX,downY;private int startX,startY;private boolean dragged,userHolding,mediaActive;private Runnable behaviorTask,reactionTask,mediaWatcher;private long lastTapAt;private BroadcastReceiver activityReceiver;
 @Override public void onCreate(){super.onCreate();sounds=new CatSoundEngine(this);audio=(AudioManager)getSystemService(AUDIO_SERVICE);createChannel();startForeground(ID,notification());registerActivityReceiver();if(Settings.canDrawOverlays(this))createOverlay();startMediaWatcher();}
 @Override public int onStartCommand(Intent i,int f,int id){return START_STICKY;}@Override public IBinder onBind(Intent i){return null;}
 private void registerActivityReceiver(){activityReceiver=new BroadcastReceiver(){@Override public void onReceive(Context c,Intent i){if(pet==null||userHolding)return;String a=i.getAction();if(PetAccessibilityService.ACTION_TYPING.equals(a))react(PetView.State.TYPING,"ketik ketik~",850);else if(PetAccessibilityService.ACTION_SCROLL.equals(a))react(PetView.State.SCROLL,null,650);}};IntentFilter f=new IntentFilter();f.addAction(PetAccessibilityService.ACTION_TYPING);f.addAction(PetAccessibilityService.ACTION_SCROLL);if(Build.VERSION.SDK_INT>=33)registerReceiver(activityReceiver,f,Context.RECEIVER_NOT_EXPORTED);else registerReceiver(activityReceiver,f);}
 private void react(PetView.State s,String text,long ms){cancelBehavior();if(reactionTask!=null)h.removeCallbacks(reactionTask);pet.setState(s);if(text!=null&&rng.nextInt(100)<16)say(text);reactionTask=()->{if(pet!=null&&!userHolding){if(mediaActive)applyMediaState();else{pet.setState(PetView.State.IDLE);scheduleNext(900);}}};h.postDelayed(reactionTask,ms);}
 private void createOverlay(){wm=(WindowManager)getSystemService(WINDOW_SERVICE);pointSize();box=PetPreferences.size(this);root=new FrameLayout(this);pet=new PetView(this);bubble=new TextView(this);bubble.setTextSize(13);bubble.setTextColor(Color.BLACK);bubble.setBackgroundColor(0xEFFFFFFF);bubble.setPadding(dp(8),dp(5),dp(8),dp(5));bubble.setVisibility(View.GONE);FrameLayout.LayoutParams pp=new FrameLayout.LayoutParams(dp((int)(box*.70f)),dp((int)(box*.70f)));pp.gravity=Gravity.BOTTOM|Gravity.CENTER_HORIZONTAL;FrameLayout.LayoutParams bp=new FrameLayout.LayoutParams(-2,-2);bp.gravity=Gravity.TOP|Gravity.CENTER_HORIZONTAL;root.addView(bubble,bp);root.addView(pet,pp);int type=Build.VERSION.SDK_INT>=26?WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY:WindowManager.LayoutParams.TYPE_PHONE;int flags=WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE|WindowManager.LayoutParams.FLAG_NOT_TOUCH_MODAL|WindowManager.LayoutParams.FLAG_LAYOUT_NO_LIMITS|WindowManager.LayoutParams.FLAG_LAYOUT_IN_SCREEN;lp=new WindowManager.LayoutParams(dp(box),dp(box),type,flags,PixelFormat.TRANSLUCENT);lp.gravity=Gravity.TOP|Gravity.START;lp.x=Math.max(0,screenW/2-lp.width/2);lp.y=Math.max(0,screenH-lp.height-dp(70));wm.addView(root,lp);root.setOnTouchListener((v,e)->touch(e));scheduleNext(1000);}
 private boolean touch(MotionEvent e){switch(e.getActionMasked()){case MotionEvent.ACTION_DOWN:userHolding=true;cancelBehavior();if(reactionTask!=null)h.removeCallbacks(reactionTask);downX=e.getRawX();downY=e.getRawY();startX=lp.x;startY=lp.y;dragged=false;pet.setState(PetView.State.HAPPY);return true;case MotionEvent.ACTION_MOVE:float dx=e.getRawX()-downX,dy=e.getRawY()-downY;if(Math.abs(dx)>8||Math.abs(dy)>8)dragged=true;lp.x=clamp(startX+(int)dx,0,Math.max(0,screenW-lp.width));lp.y=clamp(startY+(int)dy,0,Math.max(0,screenH-lp.height));wm.updateViewLayout(root,lp);return true;case MotionEvent.ACTION_UP:case MotionEvent.ACTION_CANCEL:userHolding=false;if(!dragged){needs.pet();long now=SystemClock.uptimeMillis();boolean dbl=now-lastTapAt<380;lastTapAt=now;String cat=PetPreferences.cat(this);if(dbl){sounds.playFor(cat,true);say("YUKI".equals(cat)||"REN".equals(cat)?"nyaa~ ♡":"meow!");needs.play();pet.setState(PetView.State.PLAY);}else{sounds.playRandom(cat);pet.setState(PetView.State.HAPPY);say("YUKI".equals(cat)?"nyaa~":"REN".equals(cat)?"nyan":"TORA".equals(cat)?"mrrrow":"meow~");}}else pet.setState(PetView.State.IDLE);if(mediaActive)h.postDelayed(this::applyMediaState,700);else scheduleNext(1400);return true;}return false;}
 private void startMediaWatcher(){mediaWatcher=new Runnable(){@Override public void run(){boolean now=false;try{now=audio!=null&&audio.isMusicActive();}catch(Exception ignored){}if(now!=mediaActive){mediaActive=now;if(root!=null&&!userHolding){if(mediaActive){cancelBehavior();applyMediaState();}else if(pet!=null&&(pet.getState()==PetView.State.MEDIA_WATCH||pet.getState()==PetView.State.MUSIC)){pet.setState(PetView.State.IDLE);scheduleNext(900);}}}else if(mediaActive&&root!=null&&!userHolding&&(pet.getState()==PetView.State.IDLE||pet.getState()==PetView.State.SIT||pet.getState()==PetView.State.LOOK_AROUND))applyMediaState();h.postDelayed(this,1200);}};h.post(mediaWatcher);}
 private void applyMediaState(){if(pet==null||userHolding)return;cancelBehavior();boolean headphones=headphonesConnected();PetView.State target=headphones?PetView.State.MUSIC:PetView.State.MEDIA_WATCH;pet.setState(target);if(rng.nextInt(100)<8)say(headphones?"♪ nyan~ ♪":(rng.nextBoolean()?"popcorn time 🍿":"cola dulu~"));}
 private boolean headphonesConnected(){if(audio==null)return false;try{AudioDeviceInfo[] d=audio.getDevices(AudioManager.GET_DEVICES_OUTPUTS);for(AudioDeviceInfo x:d){int t=x.getType();if(t==AudioDeviceInfo.TYPE_WIRED_HEADPHONES||t==AudioDeviceInfo.TYPE_WIRED_HEADSET||t==AudioDeviceInfo.TYPE_BLUETOOTH_A2DP||t==AudioDeviceInfo.TYPE_BLUETOOTH_SCO||t==AudioDeviceInfo.TYPE_USB_HEADSET)return true;}}catch(Exception ignored){}return false;}
 private void scheduleNext(long d){cancelBehavior();behaviorTask=()->{if(root==null||userHolding)return;if(mediaActive){applyMediaState();return;}needs.tick();smart();};h.postDelayed(behaviorTask,d);}private void cancelBehavior(){if(behaviorTask!=null)h.removeCallbacks(behaviorTask);}
 private void smart(){if(mediaActive){applyMediaState();return;}if(needs.tired()&&rng.nextInt(100)<72){activity(PetView.State.SLEEP,7000,"zzZ...");needs.sleep();return;}if(needs.hungry()&&rng.nextInt(100)<68){activity(PetView.State.EAT,4300,"nyam nyam");needs.eat();return;}if(needs.lonely()&&rng.nextInt(100)<55){activity(PetView.State.ATTENTION,3200,"main sama aku dong 🐾");return;}if(needs.playful()&&rng.nextInt(100)<25){walk(true);needs.play();return;}int r=rng.nextInt(100);if(r<25)walk(false);else if(r<33)walk(true);else if(r<43)activity(PetView.State.SIT,3500,null);else if(r<52)activity(PetView.State.GROOM,4000,null);else if(r<60)activity(PetView.State.STRETCH,2200,"mreeeng~");else if(r<67)activity(PetView.State.SCRATCH,2600,null);else if(r<74)activity(PetView.State.LOOK_AROUND,3000,"apa tuh?");else if(r<82){activity(PetView.State.PLAY,4000,"main 😸");needs.play();}else if(r<88){activity(PetView.State.DRINK,3000,"minum dulu");needs.drink();}else if(r<94)activity(PetView.State.KNEAD,3500,"bikin roti~");else activity(PetView.State.YAWN,2200,"huaaam...");}
 private void walk(boolean run){if(mediaActive){applyMediaState();return;}pet.setState(run?PetView.State.RUN:PetView.State.WALK);int dir=rng.nextBoolean()?1:-1;pet.setFacing(dir);int base=run?26:13;int speed=Math.max(1,PetPreferences.speed(this));int steps=8+rng.nextInt(10);final int[] n={0};behaviorTask=new Runnable(){public void run(){if(root==null||userHolding)return;if(mediaActive){applyMediaState();return;}lp.x=clamp(lp.x+dir*Math.max(2,base*speed/100),0,Math.max(0,screenW-lp.width));wm.updateViewLayout(root,lp);if(++n[0]<steps)h.postDelayed(this,110);else{pet.setState(PetView.State.IDLE);scheduleNext(1200+rng.nextInt(2200));}}};h.post(behaviorTask);}
 private void activity(PetView.State s,long d,String speech){pet.setState(s);if(speech!=null)say(speech);behaviorTask=()->{if(root==null||userHolding)return;if(mediaActive){applyMediaState();return;}pet.setState(PetView.State.IDLE);scheduleNext(1300+rng.nextInt(2500));};h.postDelayed(behaviorTask,d);}
 private void say(String s){bubble.setText(s);bubble.setVisibility(View.VISIBLE);h.postDelayed(()->{if(bubble!=null)bubble.setVisibility(View.GONE);},2200);}
 private void pointSize(){android.util.DisplayMetrics m=new android.util.DisplayMetrics();wm=(WindowManager)getSystemService(WINDOW_SERVICE);wm.getDefaultDisplay().getRealMetrics(m);screenW=m.widthPixels;screenH=m.heightPixels;}
 private int clamp(int v,int a,int b){return Math.max(a,Math.min(b,v));}private int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}
 private void createChannel(){if(Build.VERSION.SDK_INT>=26){NotificationChannel c=new NotificationChannel("ric_pet","RIC Pet",NotificationManager.IMPORTANCE_LOW);getSystemService(NotificationManager.class).createNotificationChannel(c);}}
 private Notification notification(){Intent i=new Intent(this,MainActivity.class);PendingIntent p=PendingIntent.getActivity(this,0,i,PendingIntent.FLAG_IMMUTABLE|PendingIntent.FLAG_UPDATE_CURRENT);return new Notification.Builder(this,"ric_pet").setContentTitle("RIC Pet aktif").setContentText("Pet tetap aktif saat kamu menonton atau mendengarkan musik").setSmallIcon(R.drawable.ic_notification).setContentIntent(p).build();}
 @Override public void onDestroy(){cancelBehavior();h.removeCallbacksAndMessages(null);if(activityReceiver!=null)try{unregisterReceiver(activityReceiver);}catch(Exception ignored){}if(root!=null&&wm!=null)try{wm.removeView(root);}catch(Exception ignored){}super.onDestroy();}
}
